### ISSUE TITLE
Undocumented requirements, "check" and "underscore"

### ISSUE THREAD

**Issue by btoueg** [gadicc/meteor-headers#45]
I have no clue how the package is built by Meteor, but what I know is that `$HOME/.meteor/packages/gadicohen_headers/.0.0.30.1z0jjj3++os+web.browser+web.cordova/os.json` lacks the `underscore` dependency.

It's causing me trouble when testing my package (see https://github.com/meteor-velocity/velocity/issues/411):

    ReferenceError: _ is not defined
    at ipChain (meteor://💻app/packages/gadicohen_headers/packages/gadicohen_headers.js:65:1)
    at Object.Package [as handle] (meteor://💻app/packages/gadicohen_headers/packages/gadicohen_headers.js:242:1)
    at next (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at next (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:165:78)
    at Object.Package [as handle] (meteor://💻app/packages/tap_http-methods/packages/tap_http-methods.js:375:1)
    at next (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/    
    at Object.fn [as handle] (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/    
    at next (/Users/mobeye/.meteor/packages/webapp/.1.2.2.1hpx7yg++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at Object.WebAppInternals.staticFilesMiddleware (meteor://💻app/packages/webapp/webapp_server.js:362:1)
    at meteor://💻app/packages/webapp/webapp_server.js:625:1

What tickles me is that you do reference the dependency here https://github.com/gadicc/meteor-headers/blob/master/versions.json#L147-L150, even though I don't understand the intricacies between `versions.js` and `package.js`.

Can you shed some light on this issue?

**Comment by gadicc** [comment]
hi guys, sorry for the delay... yeah, meteor 1.2 is a bit stricter; this is fixed now in the 0.0.31 release.
