### ISSUE TITLE
Exception while invoking method 'headersToken' Error: Match error: Expected Number

### ISSUE THREAD

**Issue by gabrielhpugliese** [gadicc/meteor-headers#46]
Everytime I enter on my app it raises on the server side:

```
=> App running at: http://localhost:3000/
I20151105-13:30:43.301(-2)? Exception while invoking method 'headersToken' Error: Match error: Expected Number
I20151105-13:30:43.310(-2)?     at check (packages/check/match.js:33:1)
I20151105-13:30:43.317(-2)?     at [object Object].Meteor.methods.headersToken (packages/gadicohen_headers/lib/headers-server.js:36:1)
I20151105-13:30:43.319(-2)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20151105-13:30:43.320(-2)?     at livedata_server.js:708:19
I20151105-13:30:43.321(-2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151105-13:30:43.321(-2)?     at livedata_server.js:706:40
I20151105-13:30:43.322(-2)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20151105-13:30:43.322(-2)?     at livedata_server.js:704:46
I20151105-13:30:43.322(-2)?     at tryCallTwo (/Users/gabrielpugliese/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20151105-13:30:43.322(-2)?     at doResolve (/Users/gabrielpugliese/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20151105-13:30:43.346(-2)? Sanitized and reported to the client as: Match failed [400]
```

Any idea how to fix it?

**Comment by gabrielhpugliese** [comment]
I was using `babel/polyfill` with webpack and probably it's the issue with `Number` constructor. Fixed! :)
